base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('node/<str:uuid>/', views.NodeView, name='node'),
    # path('local/<str:uuid>/', views.LocalView , name='local'),
    # path('map/', views.MapView , name='map'),
]

graph/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('back.urls')),
    path('view/', include('front.urls')),
    path('wot/', include('wot.urls')),
    path('social/', include('base.urls')),
    path('', RedirectView.as_view(pattern_name='front:graph', permanent=False)),
]

wot/urls.py
from django.urls import path
from . import views

app_name = 'wot'
urlpatterns = [
    path('api/graph/', views.GraphView , name='graph'),
    # path('view/', views.Wotmap , name='wotmap'),
]

base/models.py
from django.db import models
from polymorphic.models import PolymorphicModel
from django.core.exceptions import ValidationError

from back.models import * # core node and edge models
from back.permissions import public
from back.utils import typename

from account.permissions import userRequired

# these models come to extend the base node and edge models
# additional information (image, links, tags, account) are stored in diferents database entries
# node and edge specifications inherit from base node and edge (id, group...)
# an other instance could implement different child types (paper, lab, researcher)

class Image(models.Model):
    """ base image class, simply an URL """
    imageURL = models.CharField(max_length=2048, null=True, blank=True)
    node = models.ForeignKey(Node, on_delete=models.CASCADE, related_name="image")

class Tag(models.Model):
    tag = models.CharField(max_length=64, unique=True)
    related = models.ManyToManyField(DBO, related_name="tags")
    def __str__(self):
        return self.tag

# =============================================

# LinkKinds = (
#     # external edge kinds (to external (non-graph) node kind resource)
#     ('website', 'Website'), # simple link to website, reciprocal: <a rel="me" href="https://graph.net/@h30x"></a>
#     ('email', 'Email'), # simple link to email, reciprocal: verify email address
#     ('address', 'Address'), # simple link to adress, reciprocal: address verified by post mail
#     ('mastodon', 'Mastodon'), # ...
#     ('diaspora', 'Diaspora'),
#     ('pixelfed', 'Pixelfed'),
#     ('facebook', 'Facebook'),
#     ('twitter', 'Twitter'),
#     ('instagram', 'Instagram'),
#     ('linkedIn', 'LinkedIn'),
#     # federated edge kinds (to external graph node)
#     ('unknown', 'Unknown'), # simple link to other node, edge kind not known (node kind or edge kind not implemented locally)
#     ('isonym', 'Isonym'), # symmetrical link between two id nodes on different instances
#         # add local types supported by distant instance (EdgeKind.Kinds)
# )


class Link(PolymorphicModel):
    anchor = models.ForeignKey(Node, on_delete=models.CASCADE, related_name="links")
    def __str__(self):
        return f"{typename(self)} on {self.anchor}"

class Website(Link):
    """ link to website """
    verified = models.BooleanField(default=False)
    url = models.CharField(max_length=256)
    def tryValidate(self):
        """ tries to validate the link by looking for <a rel="me" href="https://graph.net/id"></a>
        in the website and turns verified to on if so """
        pass
    def __str__(self):
        return super().__str__() + f": {self.url}"
    def fa(self): # font-awesome
        return "fa-globe"


# =============================================

# node kinds

@public
@userRequired
# TODO provide a decorator for name unique
class Identity(Node): # identity corresponding to a physical or moral person
    def nameExists(self):
        try:
            Identity.objects.get(name=self.name)
            return True
        except Identity.MultipleObjectsReturned:
            return True
        except Identity.DoesNotExist: # normal behavior
            return False
    def assertNameUnique(self):
        if self.nameExists():
            raise ValidationError("an identity with this name already exists")
    def creatable(self, **kwargs): # verifies if node is correct
        self.assertNameUnique()
        super().creatable(**kwargs)
    def editable(self, **kwargs): # verifies if node is correct
        self.assertNameUnique()
        super().editable(**kwargs)

@public
@userRequired
class Group(Node): # group of peoples / identities
    isOpen = models.BooleanField(default=True)
    def isEditableBy(self, account): # overwrites isEditableBy method
        if self.isOpen:
            return True
        else:
            return account.canEdit(self)
    # TODO add signal to add reciprocal link automatically if group is open

# return ({'kind': "member", 'message': {'ask': "ask to be member", 'asked': "membership requested", 'accept': "accept membership invitation", 'status': "member"}},

# edge kinds

@public
class Follow(Edge): # simple forward link (identity → node) attesting interest
    Symmetrical = False # no need of a symmetric link to be active (not needed since it's default)
    AllowedFromTo = { (Identity, Node) }
    Message = {
        'none': "follow",
        'forward': "following",
        'backward': "follow back",
        'both': "following",
    }

@public
class Membership(Edge): # group appartenance symmetrical link (node ←→ node:group)
    Symmetrical = True # needs a symmetric link to be considered as active
    AllowedFromTo = { (Node, Group), (Group, Node) }
    Message = {
        'none': "request membership",
        'forward': "membership request send",
        'backward': "accept membership request",
        'both': "member",
    }

# ============================================


# def isAllowed(Type, From, To):
#     return (From, To) in Type.AllowedFromTo # check is from/to pair is allowed

base/views.py
from django.shortcuts import render, get_object_or_404

from back.models import DBO

# Create your views here.

def NodeView(request, uuid):
    cNode = get_object_or_404(DBO, pk=uuid)

    try:
        uNode = request.user.authmethod.account.node()
    except: # e.g. anonymous user
        uNode = False

    if uNode == cNode or uNode == None:
        interact = False
    else:
        interact = uNode.actions(cNode)

    editable = cNode.isEditableBy(request.user)

    links = cNode.links.all()
    tags = cNode.tags.all()

    # TODO insert the following in a Node method
    edgesFrom = cNode.edgeFrom.all()

    rel = cNode.allRelatives()
    relatives = {}
    for kind, edgelist in rel.items():
        if edgelist:
            relatives.update({kind.__name__: edgelist})

    context = {'node': cNode, 'links': links, 'tags': tags, 'interact': interact, 'relatives': relatives,
    'uNode': uNode}
    return render(request, 'base/node.html', context)

base/templates/base/node.html
{% load static %}


<!doctype html>
<html>
<head>
  <meta charset="utf8"/>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.5/css/fork-awesome.min.css" integrity="sha256-P64qV9gULPHiZTdrS1nM59toStkgjM0dsf5mK/UwBV4=" crossorigin="anonymous">
  <style>
    #info { border: solid 1px gray;}
  </style>

  <script src="{% static 'front/js/mithril-v2.0.0.js' %}"></script>
  <script src="{% static 'front/js/jquery-3.3.1.slim.min.js' %}"></script>

  <script>

  // get cookie
  function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }

  // send object (action can be create, update, or delete)
  function sendObject(action, data) {
    var csrftoken = getCookie('csrftoken');
    m.request({
      method: "POST",
      url: "http://localhost:8000/api/" + action + "/",
      data: data,
      headers: {'X-CSRFTOKEN': csrftoken},
    })
    .then( function(result) { // success
        RESPONSE = result
    })
    .catch(function(error) { // error : do nothing
        RESPONSE = error.response
    })
  }
  </script>

</head>
<body>
  logged in as: {{ user }} <br>
  account: {{ user.authmethod.account }}<br>
  account node: {{ user.authmethod.account.node }}<br>
  node: {{uNode }}<br><br>

  {% if interact %}
    {% for action in interact %}
      <button onclick="sendObject('{{action.name}}', {type: '{{action.type}}', source: {uuid:'{{action.source.pk}}'}, target: {uuid: '{{action.source.pk}}'} } )"> {{action.message}} </button>
    {% endfor %}
  {% endif %}

  <div id="info">
  <h2>{{ node.name }} <a href="{% url 'base:node' node.pk %}">#</a></h2>
  <ul>
  {% for link in links %}
    <li> <i class="fa {{link.fa}}"></i> <a href="{{link.url}}">{{link.url}}</a> </li>
  {% endfor %}
  </ul>
  <ul>
  {% for tag in tags %}
    <li> <a href="#">#{{tag.tag}}</a> </li>
  {% endfor %}
  </ul>
  {% for type, rels in relatives.items %}
    {{ type }}:
    <ul>
      {% for rel in rels %}
        <a href="{% url 'base:node' rel.toNode.pk %}">{{rel.toNode}}</a>
      {% endfor %}
    </ul>
  {% endfor %}
  </div>

  {% if editable %}
  <div id="manage">
    <!-- it may be better to do an app instead of POSTing forms -->
  </div>
  {% endif %}

  <p>Watch on graph to see relations</p>
</body>
</html>